require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BbsThreadsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BbsThread. As you add validations to BbsThread, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BbsThreadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bbs_threads as @bbs_threads" do
      bbs_thread = BbsThread.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bbs_threads)).to eq([bbs_thread])
    end
  end

  describe "GET #show" do
    it "assigns the requested bbs_thread as @bbs_thread" do
      bbs_thread = BbsThread.create! valid_attributes
      get :show, {:id => bbs_thread.to_param}, valid_session
      expect(assigns(:bbs_thread)).to eq(bbs_thread)
    end
  end

  describe "GET #new" do
    it "assigns a new bbs_thread as @bbs_thread" do
      get :new, {}, valid_session
      expect(assigns(:bbs_thread)).to be_a_new(BbsThread)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bbs_thread as @bbs_thread" do
      bbs_thread = BbsThread.create! valid_attributes
      get :edit, {:id => bbs_thread.to_param}, valid_session
      expect(assigns(:bbs_thread)).to eq(bbs_thread)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BbsThread" do
        expect {
          post :create, {:bbs_thread => valid_attributes}, valid_session
        }.to change(BbsThread, :count).by(1)
      end

      it "assigns a newly created bbs_thread as @bbs_thread" do
        post :create, {:bbs_thread => valid_attributes}, valid_session
        expect(assigns(:bbs_thread)).to be_a(BbsThread)
        expect(assigns(:bbs_thread)).to be_persisted
      end

      it "redirects to the created bbs_thread" do
        post :create, {:bbs_thread => valid_attributes}, valid_session
        expect(response).to redirect_to(BbsThread.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bbs_thread as @bbs_thread" do
        post :create, {:bbs_thread => invalid_attributes}, valid_session
        expect(assigns(:bbs_thread)).to be_a_new(BbsThread)
      end

      it "re-renders the 'new' template" do
        post :create, {:bbs_thread => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bbs_thread" do
        bbs_thread = BbsThread.create! valid_attributes
        put :update, {:id => bbs_thread.to_param, :bbs_thread => new_attributes}, valid_session
        bbs_thread.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bbs_thread as @bbs_thread" do
        bbs_thread = BbsThread.create! valid_attributes
        put :update, {:id => bbs_thread.to_param, :bbs_thread => valid_attributes}, valid_session
        expect(assigns(:bbs_thread)).to eq(bbs_thread)
      end

      it "redirects to the bbs_thread" do
        bbs_thread = BbsThread.create! valid_attributes
        put :update, {:id => bbs_thread.to_param, :bbs_thread => valid_attributes}, valid_session
        expect(response).to redirect_to(bbs_thread)
      end
    end

    context "with invalid params" do
      it "assigns the bbs_thread as @bbs_thread" do
        bbs_thread = BbsThread.create! valid_attributes
        put :update, {:id => bbs_thread.to_param, :bbs_thread => invalid_attributes}, valid_session
        expect(assigns(:bbs_thread)).to eq(bbs_thread)
      end

      it "re-renders the 'edit' template" do
        bbs_thread = BbsThread.create! valid_attributes
        put :update, {:id => bbs_thread.to_param, :bbs_thread => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bbs_thread" do
      bbs_thread = BbsThread.create! valid_attributes
      expect {
        delete :destroy, {:id => bbs_thread.to_param}, valid_session
      }.to change(BbsThread, :count).by(-1)
    end

    it "redirects to the bbs_threads list" do
      bbs_thread = BbsThread.create! valid_attributes
      delete :destroy, {:id => bbs_thread.to_param}, valid_session
      expect(response).to redirect_to(bbs_threads_url)
    end
  end

end
